services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/mlflow.db
      --default-artifact-root file:/mlflow/artifacts
      --host 0.0.0.0
      --port 5000
    ports:
      - "5000:5000"      # external access
    volumes:
      - ./mlflow:/mlflow

  uploader:
    build: ./uploader
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - S3_BUCKET
    profiles:
      - manual

  trainer:
    build: ./trainer
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - S3_BUCKET
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    volumes:
      - ./mlflow:/app/mlflow
